name: First Py Scraper

on:
  workflow_dispatch:
    inputs:
      state:
        description: 'US state to scrape'
        required: true
        default: 'ny'
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install BLN Scraper
        run: pip install warn-scraper
        
      - name: Scrape WARN data
        run: warn-scraper ${{ inputs.state }} --data-dir ./data/
        
      - name: Date stamp
        run: date > ./data/latest-scrape-date.txt
        
      - name: Commit and push
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@users.noreply.github.com"
          git add ./data/
          git commit -m "Latest data for ${{ inputs.state}}" && git push || true


          
      

  
